pipeline:
  - stage: vad
    model: SileroVADProcessor
    params:
      model_path: ""
      threshold: 0.5
      min_silence_duration_ms: 1000
      min_speech_duration_ms: 1000

  - stage: asr
    model: FasterWhisperProcessor
    params:
      model_size_or_path: "tiny.en"
      device: cpu
      compute_type: int8

  - stage: mt
    model: HelsinkiEnRuProcessor
    params:
      model_path: ""
      device: cpu

  - stage: tts
    model: SileroTTSProcessor
    params:
      model_path: ""
      device: cpu
      speaker: xenia


temp-dir: "./video-dubbing-temp-dir"